version: '3'
services:
  app:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      # node_modulesを上書きしないようにする（ここが重要）
      - ./build:/app/build
    environment:
      - CHOKIDAR_USEPOLLING=true

